/**
 * Generates src/lib/theme/tokens.css from the token source of truth in
 * src/lib/theme/tokens.ts. Run with `pnpm tokens`.
 *
 * Output strategy (pure CSS, no flash-of-unstyled-content):
 *   :root                       → light values (the always-present baseline)
 *   :root[data-theme='dark']    → dark values (explicit user choice)
 *   @media (prefers-color-scheme: dark) :root:not([data-theme='light'])
 *                               → dark values (OS preference, unless user forced light)
 *
 * The theme store only toggles the `data-theme` attribute; the cascade does the rest.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { colorTokens } from '../src/lib/theme/tokens.ts';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/lib/theme/tokens.css');

const entries = Object.entries(colorTokens);
const decls = (mode: 'light' | 'dark', indent: string) =>
	entries.map(([name, v]) => `${indent}${name}: ${v[mode]};`).join('\n');

const css = `/* AUTO-GENERATED by scripts/gen-tokens.ts — do not edit by hand.
   Edit src/lib/theme/tokens.ts and run \`pnpm tokens\`. */

:root {
${decls('light', '\t')}
}

:root[data-theme='dark'] {
${decls('dark', '\t')}
}

@media (prefers-color-scheme: dark) {
	:root:not([data-theme='light']) {
${decls('dark', '\t\t')}
	}
}
`;

writeFileSync(out, css);
console.log(`Wrote ${entries.length} tokens × 2 themes → ${out}`);
