// Snapshot the spec's custom icon set (spec/ui-standards/icons/*.svg) into a single
// TS module. Each icon keeps its own viewBox and inner markup; icons use currentColor
// so they theme via the surrounding text colour (spec ui-standards/icons.md).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = join(here, '..', '..', 'spec', 'ui-standards', 'icons');
const outFile = join(here, '..', 'src', 'lib', 'icons', 'icons.ts');

const files = readdirSync(iconsDir).filter((f) => f.endsWith('.svg'));
const entries = [];

// Presentational attributes that live on the outer <svg> and must be carried onto
// the rendered <svg> so glyphs paint with currentColor (fill vs stroke) — not the
// default black fill. viewBox/xmlns/width/height/class are handled separately.
const PRESENTATION_ATTRS = ['fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin'];

for (const file of files) {
  const name = file.replace(/\.svg$/, '');
  const raw = readFileSync(join(iconsDir, file), 'utf8');
  const openTag = (raw.match(/<svg[^>]*>/) || [''])[0];
  const viewBox = (openTag.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 24 24';

  const attrs = {};
  for (const attr of PRESENTATION_ATTRS) {
    const m = openTag.match(new RegExp(`${attr}="([^"]+)"`));
    if (m) attrs[attr] = m[1];
  }

  // Inner markup between the outer <svg ...> and </svg>.
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  entries.push({ name, viewBox, attrs, inner });
}

entries.sort((a, b) => a.name.localeCompare(b.name));

const body = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.name)}: { viewBox: ${JSON.stringify(e.viewBox)}, attrs: ${JSON.stringify(e.attrs)}, body: ${JSON.stringify(e.inner)} },`,
  )
  .join('\n');

const out = `// GENERATED by scripts/gen-icons.js from spec/ui-standards/icons/*.svg — do not edit.
export type IconDef = { viewBox: string; attrs: Record<string, string>; body: string };
export const ICONS: Record<string, IconDef> = {
${body}
};
export type IconName = keyof typeof ICONS;
`;

writeFileSync(outFile, out);
console.log(`Wrote ${entries.length} icons to ${outFile}`);
