/**
 * Generates src/theme/tokens.css from the token source in src/theme/tokens.ts.
 * Run with `pnpm tokens`.
 *
 * Output strategy (pure CSS, no flash-of-unstyled-content):
 *   :root                       → light values (always-present baseline)
 *   :root[data-theme='dark']    → dark values (explicit user choice)
 *   :root[data-theme='mui']     → existing-app (MUI reference) values
 *   @media (prefers-color-scheme: dark) :root:not([data-theme])
 *                               → dark values (OS preference; only when no explicit theme)
 *
 * The theme controller only toggles the `data-theme` attribute; the cascade does the rest.
 * MUI values default to the light value (mui ?? light) — see tokens.ts.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { colorTokens, type TokenValue } from '../src/theme/tokens.ts';

/** Convert the spec's value notation to a CSS colour.
 *  `#RRGGBB` → itself; `#RRGGBB @ NN%` → `rgba(r,g,b, NN/100)` (never rgba() in the spec). */
function toCss(value: string): string {
  const m = /^(#[0-9A-Fa-f]{6})\s*@\s*(\d+(?:\.\d+)?)%$/.exec(value.trim());
  if (!m) return value.trim();
  const hex = m[1]!;
  const alpha = Number(m[2]) / 100;
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/theme/tokens.css');

const entries = Object.entries(colorTokens) as [string, TokenValue][];
const decls = (mode: 'light' | 'dark' | 'mui', indent: string) =>
  entries
    .map(([name, v]) => {
      const raw = mode === 'mui' ? (v.mui ?? v.light) : v[mode];
      return `${indent}${name}: ${toCss(raw)};`;
    })
    .join('\n');

const css = `/* AUTO-GENERATED by scripts/gen-tokens.ts — do not edit by hand.
   Edit src/theme/tokens.ts and run \`pnpm tokens\`. */

:root {
${decls('light', '  ')}
}

:root[data-theme='dark'] {
${decls('dark', '  ')}
}

:root[data-theme='mui'] {
${decls('mui', '  ')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${decls('dark', '    ')}
  }
}
`;

writeFileSync(out, css);
console.log(`Wrote ${entries.length} tokens × 3 themes → ${out}`);
